// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    CarbonLogoLinkedin: typeof import('virtual:vite-icons/carbon/logo-linkedin')['default']
    CarbonLogoTwitter: typeof import('virtual:vite-icons/carbon/logo-twitter')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    RiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    RiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
  }
}

export { }
